version: '3'
services:
  web:
    build: backend/
#    image: fastapi-test
    env_file: .env
    ports:
      - "8002:80"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - '6379:6379'
